---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minergate
  labels:
    app: minergate
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minergate
  template:
    metadata:
      labels:
        app: minergate
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - minergate
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: minergate
          image: <your minergate image>
          imagePullPolicy: Always
          args:
            - "-u"
            - "<email>"
            - "--<currency>"
